name: DevSecOps Demo CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # --- [1] SAST (Static Analysis with SonarQube) ---
      # La acción de SonarSource/sonarcloud-github-action@v1.6 usa su propio contenedor Docker con Java 11
      # Debes usar una acción que te permita controlar la versión de Java del escáner
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master # Usa la versión más reciente que es compatible con Java 17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          projectBaseDir: .

      # --- [2] SCA (Software Composition Analysis with Snyk) ---
      - name: Run Snyk scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=requirements.txt

      # --- [3] IaC Security (Infrastructure as Code with Checkov) ---
      - name: Run Checkov IaC scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: IaC/terraform/
          soft_fail: true

      # --- [4] Build Docker image ---
      - name: Build and tag Docker image
        run: docker build -t devsecops-demo:latest .

      # --- [5] DAST (Dynamic Analysis with OWASP ZAP) ---
      - name: Run the application
        run: docker-compose up -d
      
      - name: Wait for application to be ready
        run: sleep 20

      - name: Run OWASP ZAP scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:5000'