name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build, test, and analyze
    runs-on: ubuntu-latest
    steps:
      # --- [1] Checkout code ---
      - name: Checkout repository
        uses: actions/checkout@v2

      # --- [2] SAST (Static Analysis with SonarQube) ---
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          # Estos son secretos que se configuran en GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=Jkennedy2004_Ciclos
            -Dsonar.organization=Jkennedy2004

      # --- [3] SCA (Software Composition Analysis with Snyk) ---
      - name: Snyk Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # --- [4] IaC (Infrastructure as Code) Scan with Checkov ---
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true
          framework: all
          output_format: cli
          # La API key es necesaria para usar algunas características de Checkov
          api-key: ${{ secrets.BC_API_KEY }}